image: cr.d.xiaomi.net/hbase/ubuntu-openjdk1.8-maven3.5:latest

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
  KUBERNETES_CPU_REQUEST: 10
  KUBERNETES_CPU_LIMIT: 10
  KUBERNETES_MEMORY_REQUEST: 10Gi

cache:
  paths:
   - .m2/repository/

stages:
  - build
  - buildWithHadoop3
  - findbugs
  - runDevTests
  - runAllTests
  - release

build:
  stage: build
  script:
    - mvn -DskipTests clean install && mvn -DskipTests package assembly:single
    - cd $CI_PROJECT_DIR
    - tag=$(grep -e '^  <version>' pom.xml | awk -F'[><]' '{print $3}')
    - mkdir /hbase
    - tar -xvzf ${CI_PROJECT_DIR}/hbase-assembly/target/hbase-${tag}.tar.gz --strip-components 1 -C /hbase
  artifacts:
    paths:
      - hbase
  only:
    refs:
     - branch-2-mdh3
     - merge_requests

buildWithHadoop3:
  stage: buildWithHadoop3
  script:
    - mvn clean install -DskipTests -Dhadoop.profile=3.0 && mvn package assembly:single -DskipTests -Dhadoop.profile=3.0
    - tag=$(grep -e '^  <version>' pom.xml | awk -F'[><]' '{print $3}')
    - mkdir /hbase-hadoop3
    - tar -xvzf ${CI_PROJECT_DIR}/hbase-assembly/target/hbase-${tag}.tar.gz  --strip-components 1 -C /hbase-hadoop3
  artifacts:
    paths:
      - hbase-hadoop3
  only:
    refs:
     - branch-2-mdh3
     - merge_requests

findbugs:
  stage: findbugs
  script:
    - mvn findbugs:check
  only:
    refs:
      - branch-2-mdh3
      - merge_requests

runDevTests:
  stage: runDevTests
  timeout: 2 hours
  script:
    - mvn test -PrunDevTests -Dtest.exclude.pattern=**/snapshot.TestExportSnapshotWithTemporaryDirectory.java,**/snapshot.TestExportSnapshotNoCluster.java,**/snapshot.TestSecureExportSnapshotRetry.java,**/snapshot.TestMobSecureExportSnapshotRetry.java,**/snapshot.TestExportSnapshotRetry.java,org/apache/hadoop/hbase/mapreduce/*.java,org/apache/hadoop/hbase/mapred/*.java,org/apache/hadoop/hbase/mapreduce/salted/*.java
  only:
    refs:
     - branch-2-mdh3
     - merge_requests
  artifacts:
    reports:
      junit:
        - ./**/target/surefire-reports/TEST-*.xml

runAllTests:
  stage: runAllTests
  timeout: 4 hours
  script:
    - mvn test -PrunAllTests -Dtest.exclude.pattern=org/apache/hadoop/hbase/mapreduce/*.java,org/apache/hadoop/hbase/mapred/*.java,org/apache/hadoop/hbase/mapreduce/salted/*.java -fn
  only:
    refs:
     - branch-2-mdh3
  artifacts:
    reports:
      junit:
        - ./**/target/surefire-reports/TEST-*.xml

release:
  stage: release
  image:
    name: cr.d.xiaomi.net/containercloud/kaniko-executor-xiaomi:release
    entrypoint: [""]
  script:
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\"}"
    - cd $CI_PROJECT_DIR
    - tag=$(grep -e '^  <version>' pom.xml | awk -F'[><]' '{print $3}')
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - |
      /kaniko/executor \
        --context $CI_PROJECT_DIR \
        --dockerfile $CI_PROJECT_DIR/dev-support/docker-mdh/Dockerfile \
        --destination $CI_REGISTRY/hbase/hbase:$tag \
        --validate-image
    - |
      /kaniko/executor \
        --context $CI_PROJECT_DIR \
        --dockerfile $CI_PROJECT_DIR/dev-support/docker-mdh/Dockerfile \
        --destination $CI_REGISTRY/hbase/hbase:latest \
        --validate-image
    - |
      /kaniko/executor \
        --context $CI_PROJECT_DIR \
        --dockerfile $CI_PROJECT_DIR/dev-support/docker-mdh/Dockerfile-Hadoop3 \
        --destination $CI_REGISTRY/hbase/hbase-hadoop3:$tag \
        --validate-image
    - |
      /kaniko/executor \
        --context $CI_PROJECT_DIR \
        --dockerfile $CI_PROJECT_DIR/dev-support/docker-mdh/Dockerfile-Hadoop3\
        --destination $CI_REGISTRY/hbase/hbase-hadoop3:latest \
        --validate-image
  only:
    refs:
      - branch-2-mdh3
