image: cr.d.xiaomi.net/hbase/ubuntu-openjdk1.8-maven3.5:latest

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
  KUBERNETES_CPU_REQUEST: 10
  KUBERNETES_CPU_LIMIT: 10
  KUBERNETES_MEMORY_REQUEST: 10Gi

cache:
  paths:
   - .m2/repository/

stages:
  - build
  - runDevTests
  - runAllTests

build:
  stage: build
  script:
    - mvn -DskipTests clean install && mvn -DskipTests package assembly:single
  only:
    refs:
     - branch-2-mdh3
     - merge_requests

runDevTests:
  stage: runDevTests
  timeout: 2 hours
  script:
    - mvn test -PrunDevTests -Dtest.exclude.pattern=**/snapshot.TestExportSnapshotWithTemporaryDirectory.java,**/snapshot.TestExportSnapshotNoCluster.java,**/snapshot.TestSecureExportSnapshotRetry.java,**/snapshot.TestMobSecureExportSnapshotRetry.java,**/snapshot.TestExportSnapshotRetry.java,org/apache/hadoop/hbase/mapreduce/*.java,org/apache/hadoop/hbase/mapred/*.java
  only:
    refs:
     - branch-2-mdh3
     - merge_requests

runAllTests:
  stage: runAllTests
  timeout: 4 hours
  script:
    - mvn test -PrunAllTests -Dtest.exclude.pattern=org/apache/hadoop/hbase/mapreduce/*.java,org/apache/hadoop/hbase/mapred/*.java -fn
  only:
    refs:
     - branch-2-mdh3
     - merge_requests
